<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->headMeta()
            ->setCharset("utf-8")
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', 'My GPS tracks')
            ->appendName('author', 'Pedro de Oliveira')
        ?>

        <?php echo $this->headTitle('fALSO Maps')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/mine.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
         ?>
    </head>

    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">fALSO Maps</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <?php echo $this->
                    navigation('Zend\Navigation\Default')
                    ->menu()
                    ->setUlClass('nav navbar-nav')
                    ->setPartial('partial/bootstrap3-navbar.phtml')
                ?>
               <?php echo $this->
                    navigation('UserNavigation')
                    ->menu()
                    ->setUlClass('nav navbar-nav navbar-right')
                    ->setPartial('partial/bootstrap3-navbar.phtml')
                ?>
            </div>
          </div>
        </nav>

        <div class="container fill">

            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><?php echo $this->layout()->pageTitle; ?></h1>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <?php echo $this->content; ?>
                </div>
            </div>

        </div>

    </body>

</html>