<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->headMeta()
            ->setCharset("utf-8")
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', 'My GPS tracks')
            ->appendName('author', 'Pedro de Oliveira')
        ?>

        <?php echo $this->headTitle('fALSO Maps')->setSeparator(' - ')->setAutoEscape(false)
            ->append($trackTitle); ?>

        <?php echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/css/mine.css')
            ->prependStylesheet($this->basePath() . '/css/leaflet.elevation-0.0.4.css')
            ->prependStylesheet($this->basePath() . '/css/leaflet.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/user.js')
            ->prependFile($this->basePath() . '/js/map.js')
            ->prependFile($this->basePath() . '/js/gpx.js')
            ->prependFile($this->basePath() . '/js/leaflet.elevation-0.0.4.min.js')
            ->prependFile($this->basePath() . '/js/leaflet.js')
            ->prependFile('//d3js.org/d3.v3.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js')
         ?>

    </head>

    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">fALSO Maps</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <?php echo $this->
                    navigation('Zend\Navigation\Default')
                    ->menu()
                    ->setUlClass('nav navbar-nav')
                    ->setPartial('partial/bootstrap3-navbar.phtml')
                ?>
                <?php
                if ($user = $this->identity())
                    echo $this->partial('layout/nav-account', array('user' => $user));
                else
                    echo $this->partial('layout/nav-login');
                ?>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true"><?php echo $trackTitle ?><span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?php echo $this->url('edit-track', array('track_id' => $trackId)) ?>">Edit</a></li>
                            <li><a href="<?php echo $this->url('delete-track', array('track_id' => $trackId)) ?>">Delete</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
          </div>
        </nav>

        <div class="container-full fill">
            <?php echo $this->content; ?>
        </div>
    </body>

</html>